services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: queue
      N8N_RUNNERS_CONCURRENCY: "4"

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_secure_password_change_me

      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: "6379"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./custom-scripts:/home/node/custom-scripts
      - ./n8n-workflows:/home/node/workflows
    depends_on:
      - postgres
      - redis
    networks:
      - product-scout-net

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_secure_password_change_me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-scout-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - product-scout-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@productscout.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - product-scout-net

volumes:
  n8n_data:
  postgres_data:
  redis_data:
  pgadmin_data:


networks:
  product-scout-net:
    driver: bridge
